# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Inline-Mason
version:      0.04
version_from: lib/Inline/Mason.pm
installdirs:  site
requires:
    Inline::Files::Virtual:        0.53
    Text::MicroMason:              1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
